### ISSUE TITLE
custom nav items not appearing on local_navigation v2015100500 using Clean theme on Moodle 2.7.12

### ISSUE THREAD

**Issue by logan-reynolds** [cescobedo/moodle-local_navigation#1]
Hello,

When installing current local_navigation version 2015100500 using Clean theme on Moodle 2.7.12 (Build: 20160111), ensuring enabled is true, and using the default values for menuitems, I'm not seeing any change in the Navigation block similar to original report from Derek [here on Wed, Oct 1](https://moodle.org/plugins/local_navigation#comment-24815).  I've tried purging all caches, but unless there's another step required I believe there may be a problem with display at least on M27, and have filed this issue to investigate (or maybe just recommend in docs if there's a common configuration option that's just being missed); Thank you.

**Comment by cescobedo** [comment]
Thanks a lot Logan. I fix it. The bug is inside the lib.php. The name convention about how to extend navigation was changed. Please, pull the new version and try.

**Comment by cescobedo** [comment]
Sorry I forgot to say you than you have to download the new branch MOODLE_27_STABLE. The master branch contains the naming to Moodle 3+ and the branch MOODLE_27_STABLE the right naming for this versions. Sorry again.
