### ISSUE TITLE
Add support for languagestrings

### ISSUE THREAD

**Issue by kkiiskin** [cescobedo/moodle-local_navigation#2]
At the moment, the text added to the plugins configuration will appear the same, regardless of the language selected. Could the link-text be configured in the same way as user_menu configration:

messages,message|/message/index.php

where the string is given in the format "langstringname, componentname"

**Comment by cescobedo** [comment]
Hi Kimmo,  this feature is not developed in this plugin.  I will consider for future releases.
On the other hand, I appreciate in the future your  comments put into  the plugin url comments (https://moodle.org/plugins/local_navigation) so they can be seen by the whole community.
Thank you for your contribution.

**Comment by cescobedo** [comment]
Hi Kimmo, just new release has a translate Moodle like you want it.
