### ISSUE TITLE
sub menu can't open for theme not based on boost

### ISSUE THREAD

**Issue by Muneera-Salah** [cescobedo/moodle-local_navigation#4]
Hi ,,
I have theme not based on boost when I click menu sub menu can't open ?

**Comment by cescobedo** [comment]
Hi,

In order to help you, could you give more details? Version of Moodle. Do you know which theme is based on? Could you paste me all the menu items in order to check the syntax?

Thanks a lot and I hope to help you,

**Comment by Muneera-Salah** [comment]
Hi ,
moodle version: 3.5
theme name : remui
parent : none 
demo link
http://remui.edwiser.org/login/index.php

**Comment by Muneera-Salah** [comment]
when I used moove theme it's working very well because it's based on boost
https://moodle.org/plugins/theme_moove
but remui theme does not

**Comment by Muneera-Salah** [comment]
I follow your instruction 
Moodle community 
-Moodle free support|http://moodle.org/support 
-Moodle development|http://moodle.org/development 
--Moodle Tracker|http://tracker.moodle.org|Bugs & features|en 
--Moodle Docs|http://docs.moodle.org 
---grade,grades|https://docs.moodle.org/31/en/Grades|Docs about grades|en,es 
-Moodle News|http://moodle.org/news 
Moodle company 
-Moodle commercial hosting|http://moodle.com/hosting 
-Moodle commercial support|http://moodle.com/support

**Comment by Muneera-Salah** [comment]
**at moove theme**
![capture](https://user-images.githubusercontent.com/3780724/41964908-ed610e36-7a03-11e8-9075-dcb1ae676adb.PNG)

**at remui theme**
![image](https://user-images.githubusercontent.com/3780724/41964819-bbbab602-7a03-11e8-8ba1-b971c0c7034f.png)

**Comment by cescobedo** [comment]
Hi,

I check yours notes.

Usually, this plugins works fine with themes based on boost and clean. This Remui theme it's private theme and I can check its code.

**Comment by cescobedo** [comment]
But, this plugin uses the same functions as the Moodle Core in the custom menu items. You can see the right syntax in https://docs.moodle.org/34/en/Theme_settings#Custom_menu_items

Also, you can test the plugin with the option "Enabled Master nodes in Boost Navigation" disabled and test it and again with enable and test it.

**Comment by cescobedo** [comment]
And I'm so sorry I can't help you more, but when I can see the code of the theme it's too hard. Maybe, this theme is disabling some options.

**Comment by Mhz95** [comment]
At templates/flat_navigations.mustache
I added this code & it is working now :)
```

    {{^action}}

    <li class="site-menu-item has-sub {{#isactive}}active{{/isactive}}" data-key="{{key}}">
        <a class="m-l-{{get_indent}} has-arrow py-5" href="javascript:void(0);">
                {{#pix}}i/folder{{/pix}}

            <span class="text">{{{text}}}</span>
        </a>
        <ul class="site-menu-sub">
            {{#children}}
                {{^is_section}}
                <li class="site-menu-item ">
                        <a class="animsition-link py-5 {{#isactive}}active{{/isactive}}" href="{{{action}}}">
                          <span class="site-menu-title">{{{text}}}</span>
                        </a>
                    </li>
                {{/is_section}}
            {{/children}}
        </ul>
    </li>

    {{/action}}
```

**Comment by cescobedo** [comment]
Hi Muneera,

good idea and good job.

Cheers.
